version: '3.8'

services:
  # MySQL for application database
  mysql:
    image: mysql:8.0
    container_name: ds-ai2-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=js
      - MYSQL_USER=nerget-user
      - MYSQL_PASSWORD=nerget
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ds-ai2-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-unerget-user", "-pnerget"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch for vector search and BM25
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: ds-ai2-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=ds-ai2-cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - ds-ai2-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Ollama for local LLM and embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: ds-ai2-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ds-ai2-network
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        limits:
          memory: 8G
    command: serve

  # Model downloader - pulls required models on startup
  model-setup:
    image: ollama/ollama:latest
    container_name: ds-ai2-model-setup
    depends_on:
      - ollama
    networks:
      - ds-ai2-network
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "sleep 10 &&
       ollama pull nomic-embed-text &&
       ollama pull llama3.2-vision:11b &&
       echo 'Models downloaded successfully'"
    environment:
      - OLLAMA_HOST=http://ollama:11434

networks:
  ds-ai2-network:
    driver: bridge

volumes:
  mysql-data:
  elasticsearch-data:
  ollama-data: